# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &mandrill  
  mandrill_test_host: <%= ENV['MANDRILL_TEST_HOST'] %>
  mandrill_test_port: <%= ENV['MANDRILL_TEST_PORT'] %>
  mandrill_test_username: <%= ENV['MANDRILL_TEST_USERNAME'] %>
  mandrill_test_password: <%= ENV['MANDRILL_TEST_PASSWORD'] %>

development:
  secret_key_base: a2b97b18bedc495c75a03d3156684e80179b8d97afd4de9a6b08e14dc4fe980a2ca2bccc9dfbe47b11863a17b71cc1dd091202debaa86095a10dbe7d3ef058b3
  <<: *mandrill
  
test:
  secret_key_base: 32db1af52708899a306280e609efce53ee0be80f3874d9b8e67e60245f2ccb9c31ed4b558f6f79a886d45bebe150cb6dd2b7a54790178d844bd019e7ac0b8562
  <<: *mandrill
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
